import type { Metadata } from 'next';

import './globals.css';
import { robotoBold, robotoMedium, robotoRegular, workSans } from '@/fonts/constantsFonts';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

export const metadata: Metadata = {
  title: 'Currency Converter',
  description: 'Generated by create next app',
};

const bodyClasses = ` ${workSans.variable} ${robotoRegular.variable} ${robotoMedium.variable} ${robotoBold.variable} w-full h-screen flex flex-col`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={bodyClasses}>
        <Header />
        <main className='flex-auto'>{children}</main>
        <Footer />
      </body>
    </html>
  );
}
